### PR TITLE
Change exec vm to call

### PR DESCRIPTION
**Pull request by dixon13**
Everything can stay in line and on one thread. No need to open separate threads when running your scripts. Changed 'execVM' to 'call compile preprocessFileLineNumbers'.

### CODE REVIEW

**Comment by SpyderBlack723** [comment]
Will save this for when I rewrite it. Spawn might stay for the spawning of units as it reduces network lag that is induced by large group creations. But, as you've noticed, not necessary for 90% of what's going on.

**Comment by SpyderBlack723** [comment]
I know not everybody likes to add another mod to their collection (which is where I'm taking it - see SpyderAddons). I'll try to port it to script form once I'm done (if people still use it).

**Comment by dixon13** [comment]
ah ok I see what you're doing.

**Comment by SpyderBlack723** [comment]
https://github.com/SpyderBlack723/SpyderAddons/commit/beeb29b22224f8df1cc859b67c83f2549a88bf14

Started (and almost finished) the rewrite. Looks much cleaner, performs better, is more customizable, and leaves room for easy additions in the future.

**Pull request merged**
